import type { Template } from "../types";

export const TEMPLATES: Template[] = [
  {
    name: "Receipt 58mm",
    paperFormat: "58mm",
    sections: [
      { type: "Init" },
      { type: "Align", value: "center" },
      { type: "Bold", value: true },
      { type: "Size", value: { width: 2, height: 2 } },
      { type: "Text", value: "MY STORE" },
      { type: "Bold", value: false },
      { type: "Size", value: { width: 1, height: 1 } },
      { type: "Text", value: "123 Main Street" },
      { type: "Text", value: "Tel: 555-0100" },
      { type: "Line", value: "-" },
      { type: "Table", value: { header: ["Item", "Qty", "Price"], rows: [["Widget", "2", "$10"], ["Gadget", "1", "$20"], ["Total", "3", "$30"]], headerBold: true, separator: "single", gap: 2 } },
      { type: "Feed", value: 2 },
      { type: "Cut" },
    ],
  },
  {
    name: "Invoice A4",
    paperFormat: "A4",
    sections: [
      { type: "Align", value: "center" },
      { type: "Bold", value: true },
      { type: "Size", value: { width: 3, height: 3 } },
      { type: "Text", value: "INVOICE" },
      { type: "Bold", value: false },
      { type: "Size", value: { width: 1, height: 1 } },
      { type: "Feed" },
      { type: "Table", value: { header: ["Product", "Qty", "Unit", "Total"], rows: [["Widget A", "2", "$25", "$50"], ["Gadget B", "1", "$75", "$75"], ["Service", "3", "$40", "$120"], ["", "", "Grand Total", "$245"]], headerBold: true, separator: "single", gap: 4 } },
      { type: "Feed", value: 3 },
      { type: "Text", value: "Thank you!" },
    ],
  },
  {
    name: "QR + Barcode 80mm",
    paperFormat: "80mm",
    sections: [
      { type: "Init" },
      { type: "Align", value: "center" },
      { type: "Bold", value: true },
      { type: "Size", value: { width: 2, height: 2 } },
      { type: "Text", value: "CAFE MENU" },
      { type: "Bold", value: false },
      { type: "Size", value: { width: 1, height: 1 } },
      { type: "Line" },
      { type: "Qr", value: { data: "https://example.com/menu", size: 8, error_correction: "M" } },
      { type: "Feed" },
      { type: "Barcode", value: { data: "1234567890", barcode_type: "CODE128", height: 80, width: 3 } },
      { type: "Feed", value: 2 },
      { type: "Cut" },
    ],
  },
  {
    name: "MultiCol Layout 80mm",
    paperFormat: "80mm",
    sections: [
      { type: "Init" },
      { type: "Align", value: "center" },
      { type: "Bold", value: true },
      { type: "Size", value: { width: 2, height: 2 } },
      { type: "Text", value: "DAILY SPECIALS" },
      { type: "Bold", value: false },
      { type: "Size", value: { width: 1, height: 1 } },
      { type: "Line" },
      { type: "MultiColumn", value: { columns: [{ text: "Monday\nPasta\n$12", width: 15, align: "center" }, { text: "Tuesday\nTacos\n$10", width: 15, align: "center" }, { text: "Wednesday\nSoup\n$8", width: 15, align: "center" }], gap: 2 } },
      { type: "Feed" },
      { type: "Cut" },
    ],
  },
];
